const STEP_INFO = {
  STATE_INIT_NULL: 1,
  STATE_INIT_PROVE: 2,
  STATE_INIT_CLAIM: 3,
  STATE_INIT_RELEASE: 4,
  STATE_PROVE: 5,
  STATE_CONNECT: 6,
  STATE_SIGN_MM: 7.1,
  STATE_SIGN_KEPLR: 7.2,
  STATE_GIFT_NULL: 8,
  STATE_GIFT_NULL_ALL: 8.1,
  STATE_GIFT_CLAIME: 9,
  STATE_CLAIME_ALL: 10,
  STATE_RELEASE: 11,
};

export { STEP_INFO };
