const STEP_INFO = {
  GIFT_INFO: 0,
  PROVE_ADD: 1,
  PROVE_ADD_SELECT_SIGNER: 1.2,
  PROVE_ADD_SIGN_MM: 1.3,
  PROVE_ADD_SIGN_KEPLR: 1.4,
  PROVE_GIFT_TRUE: 1.5,
  PROVE_GIFT_FALSE: 1.6,
  CLAIME_ALL: 9,
  CLAIMED_ALL_GIFT: 10,
  RELEASE: 11,
};

export { STEP_INFO };
