[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.5", features = [] }

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
tauri = { version = "1.8.0", features = ["api-all"] }
futures = "0.3"
ipfs-api = "0.17.0"
ipfs-api-backend-hyper = "0.6"
dirs = "5.0.1"
cozo = { version = "0.7.6", features = ["storage-rocksdb"] }
warp = "0.3.7"
tokio = { version = "1.40.0", features = ["full"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
