version: '3.8'
services:
  app:
    build:
      context: .
      target: build
    ports:
      - '3000:3000'
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - CHAIN_ID=bostrom
      - RPC_URL=https://rpc.bostrom.cybernode.ai
      - LCD_URL=https://lcd.bostrom.cybernode.ai
      - WEBSOCKET_URL=wss://rpc.bostrom.cybernode.ai/websocket
      - INDEX_HTTPS=https://index.bostrom.cybernode.ai/v1/graphql
      - INDEX_WEBSOCKET=wss://index.bostrom.cybernode.ai/v1/graphql
      - CYBER_GATEWAY=https://gateway.bostrom.cybernode.ai
      - BASE_DENOM=boot
      - DENOM_LIQUID=hydrogen
      - BECH32_PREFIX=bostrom

    command: npx serve -s build
