import {
  CYBER_LINK_TRANSACTION_TYPE,
  MSG_MULTI_SEND_TRANSACTION_TYPE,
  MSG_SEND_TRANSACTION_TYPE,
} from '../../dataSource/blockchain/types';

export const BLOCKCHAIN_SYNC_INTERVAL = 60 * 1000; // 60 sec
export const PARTICLES_SYNC_INTERVAL = 60 * 1000; // 60 sec
export const MY_CHATS_SYNC_INTERVAL = 60 * 1000; // 60 sec
export const IPFS_SYNC_INTERVAL = 15 * 60 * 1000; // 15 minutes

export const MAX_PARRALEL_TRANSACTIONS = 5;
export const MAX_PARRALEL_LINKS = 20;

export const SENSE_TRANSACTIONS = [
  MSG_SEND_TRANSACTION_TYPE,
  MSG_MULTI_SEND_TRANSACTION_TYPE,
  CYBER_LINK_TRANSACTION_TYPE,
];
