export const what = [
  'Is',
  'Protocol Stack',
  'Code',
  'Consensus',
  'Knowledge',
  'Links',
  'Backlinks',
  'Decentralized Marketing (DeMa)',
  'Beneficiaries',
  'Addressing',
  'Ranking',
  'Knowledge Graph Proofs',
  'Offline and Interplanetary',
  'Internet Knowledge Protocol',
  'Smart Contracts',
  'Smart Contracts on Knowledge Graph',
  'GPU Smart Contracts',
  'Software 2.0',
  'Security',
  'Privacy',
  'Censorship',
  'Captcha',
  'Ads beneficiary',
  'Apps',
  'Robots/IoT',
  'Data Distribution',
  'Storage guaranty',
  'SuperIntelligence',
  'Browser',
  'Content Rewards',
  'Reputation',
];

export const google = [
  'Company',
  'Web2',
  'Closed',
  'USA law',
  'Private',
  'Hyperlinks',
  'No',
  'No',
  'Limited set of stakeholders',
  'URLs',
  'Blackbox',
  'No',
  'No',
  'Impossible',
  'Impossible',
  'No',
  'No',
  'No',
  'No evidence',
  'Impossible',
  'Yes',
  'Yes',
  'Google',
  'Limited',
  'Limited',
  'Private servers',
  'Impossible',
  'Non-Provable',
  'Chrome',
  'No',
  'No',
];

export const cyber = [
  'Protocol',
  'Web3',
  'Open',
  'Tendermint, Hybrid (2023)',
  'Public',
  'Cyberlinks',
  'Yes',
  'Yes',
  'Any web3 agents',
  'CIDs',
  'Sybil resistant',
  'Cyberlinks and Ranks',
  'Yes',
  'Over IBC (2021)',
  'WASM',
  'Yes',
  'Possible (2022)',
  'Yes',
  'Cryptographic proofs',
  'Possible (2024)',
  'No',
  'No',
  'Creator',
  'Unlimited',
  'Unlimited',
  'IPFS',
  'Possible, PoRep (2023)',
  'Provable',
  'Cyb',
  'Yes',
  'Yes',
];
