const networkList = [
  {
    chainId: 'osmosis-1',
    chainName: 'osmosis',
    prefix: 'osmo',
    rpc: 'https://rpc-osmosis.blockapsis.com/',
    explorerUrlToTx: 'https://www.mintscan.io/osmosis/txs/{txHash}',
    chainIdImageCid: 'QmbS1fKYo9Kxx6g2NwfqABbjKSVcNiRE4wAPYjvak2AZbN',
  },
  {
    chainId: 'cosmoshub-4',
    chainName: 'cosmos hub',
    prefix: 'cosmos',
    rpc: 'https://rpc.cosmoshub-4.cybernode.ai/',
    explorerUrlToTx: 'https://www.mintscan.io/cosmos/txs/{txHash}',
    chainIdImageCid: 'Qme1ZkS181jykkBYfvyNqUtRGEm7oCv96n6uo9wrFrMrwN',
  },
  {
    chainId: 'space-pussy',
    chainName: 'space pussy',
    prefix: 'pussy',
    rpc: 'https://rpc.space-pussy.cybernode.ai/',
    explorerUrlToTx: 'https://space-pussy.cyb.ai/network/bostrom/tx/{txHash}',
    chainIdImageCid: 'QmSdVMzpY9nuHZXZpvZdFbhhMf3nBGAe4JZ7e2Xdh6LMLr',
  },
  {
    chainId: 'juno-1',
    chainName: 'juno',
    prefix: 'juno',
    rpc: 'https://rpc-juno.itastakers.com',
    explorerUrlToTx: 'https://www.mintscan.io/juno/txs/{txHash}',
    chainIdImageCid: 'QmW3ePrLoTFQd7SqbKSZyiV429VBrXpvAYS5Xa4Nt1kVYe',
  },
  {
    chainId: 'gravity-bridge-3',
    chainName: 'gravity bridge',
    prefix: 'gravity',
    rpc: 'https://gravitychain.io:26657',
    explorerUrlToTx: 'https://www.mintscan.io/gravity-bridge/txs/{txHash}',
    chainIdImageCid: 'QmQdHDccKswnYjBUML5j3m78NdZWmJ2BTPwMqrGeD73cRQ',
  },
  {
    chainId: 'desmos-mainnet',
    chainName: 'desmos',
    prefix: 'desmos',
    rpc: 'https://rpc.mainnet.desmos.network',
    explorerUrlToTx: 'https://www.mintscan.io/desmos/txs/{txHash}',
    chainIdImageCid: 'QmUmhmyiQfYgJFWjMQF6W8GGvtjAF9YwcTLwnjijDFhmVP',
  },
  {
    chainId: 'evmos_9001-2',
    chainName: 'evmos',
    rpc: 'https://tendermint.bd.evmos.org:26657',
    prefix: 'evmos',
    explorerUrlToTx: 'https://www.mintscan.io/evmos/txs/{txHash}',
    chainIdImageCid: 'QmXhPaHEpLakqEvhY36bzt3ffi9HheF8haPNdbf8RKJbko',
  },
  {
    chainId: 'chihuahua-1',
    chainName: 'chihuahua',
    prefix: 'chihuahua',
    rpc: 'https://rpc.chihuahua.wtf',
    explorerUrlToTx: 'https://www.mintscan.io/chihuahua/txs/{txHash}',
    chainIdImageCid: 'QmdmPzgP3sps9Qbc23VsoaBjBR9cVegonHapTBpN96tjmh',
  },
  {
    chainId: 'axelar-dojo-1',
    chainName: 'axelar',
    prefix: 'axelar',
    rpc: 'https://rpc-1.axelar.nodes.guru',
    explorerUrlToTx: 'https://mintscan.io/axelar/txs/{txHash}',
    chainIdImageCid: 'QmdmPzgP3sps9Qbc23VsoaBjBR9cVegonHapTBpN96tjmh',
  },
];

export default networkList;
