const tokenList = [
  {
    coinMinimalDenom: 'uatom',
    counterpartyChainId: 'cosmoshub-4',
    sourceChannelId: 'channel-341',
    destChannelId: 'channel-8',
    coinDecimals: 6,
    denom: 'ATOM',
    coinImageCid: 'Qme1ZkS181jykkBYfvyNqUtRGEm7oCv96n6uo9wrFrMrwN',
  },
  {
    coinMinimalDenom: 'ujuno',
    counterpartyChainId: 'juno-1',
    sourceChannelId: 'channel-93',
    destChannelId: 'channel-10',
    coinDecimals: 6,
    denom: 'JUNO',
    coinImageCid: 'QmW3ePrLoTFQd7SqbKSZyiV429VBrXpvAYS5Xa4Nt1kVYe',
  },
  {
    coinMinimalDenom: 'ugraviton',
    counterpartyChainId: 'gravity-bridge-3',
    sourceChannelId: 'channel-103',
    destChannelId: 'channel-12',
    coinDecimals: 6,
    denom: 'GRAV',
    coinImageCid: 'QmQdHDccKswnYjBUML5j3m78NdZWmJ2BTPwMqrGeD73cRQ',
  },
  {
    coinMinimalDenom: 'gravity0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    counterpartyChainId: 'gravity-bridge-3',
    sourceChannelId: 'channel-103',
    destChannelId: 'channel-12',
    coinDecimals: 18,
    denom: 'gravETH',
    coinImageCid: 'Qmf4ByG3Z6ptN7EMDEVNukzXNAEZLwzyo4FM6WNJ1rciYA',
  },
  {
    coinMinimalDenom: 'pussy',
    counterpartyChainId: 'space-pussy',
    sourceChannelId: 'channel-0',
    destChannelId: 'channel-11',
    coinDecimals: 0,
    denom: 'PUSSY',
    coinImageCid: 'QmSdVMzpY9nuHZXZpvZdFbhhMf3nBGAe4JZ7e2Xdh6LMLr',
  },
  {
    coinMinimalDenom: 'uosmo',
    counterpartyChainId: 'osmosis-1',
    sourceChannelId: 'channel-95',
    destChannelId: 'channel-2',
    coinDecimals: 6,
    denom: 'OSMO',
    coinImageCid: 'QmbS1fKYo9Kxx6g2NwfqABbjKSVcNiRE4wAPYjvak2AZbN',
  },
  {
    coinMinimalDenom: 'udsm',
    counterpartyChainId: 'desmos-mainnet',
    sourceChannelId: 'channel-6',
    destChannelId: 'channel-13',
    coinDecimals: 6,
    denom: 'DSM',
    coinImageCid: 'QmUmhmyiQfYgJFWjMQF6W8GGvtjAF9YwcTLwnjijDFhmVP',
  },
  {
    coinMinimalDenom: 'uhuahua',
    counterpartyChainId: 'chihuahua-1',
    sourceChannelId: 'channel-95',
    destChannelId: 'channel-12',
    coinDecimals: 6,
    denom: 'HUAHUA',
    coinImageCid: 'QmdmPzgP3sps9Qbc23VsoaBjBR9cVegonHapTBpN96tjmh',
  },
  {
    coinMinimalDenom: 'aevmos',
    counterpartyChainId: 'evmos_9001-2',
    sourceChannelId: 'channel-19',
    destChannelId: 'channel-9',
    coinDecimals: 18,
    denom: 'EVMOS',
    coinImageCid: 'QmXhPaHEpLakqEvhY36bzt3ffi9HheF8haPNdbf8RKJbko',
  },
  {
    coinDecimals: 3,
    denom: 'A',
    coinMinimalDenom: 'milliampere',
    counterpartyChainId: 'bostrom',
  },
  {
    coinDecimals: 0,
    denom: 'H',
    coinMinimalDenom: 'hydrogen',
    counterpartyChainId: 'bostrom',
  },
  {
    coinDecimals: 0,
    denom: 'LP',
    coinMinimalDenom: 'liquidpussy',
  },
  {
    coinDecimals: 3,
    denom: 'V',
    coinMinimalDenom: 'millivolt',
    counterpartyChainId: 'bostrom',
  },
];

export default tokenList;
