const steps = {
  STEP_INIT: 0,
  STEP_NICKNAME: 1,
  STEP_RULES: 2,
  STEP_AVATAR_UPLOAD: 3,
  STEP_KEPLR_INIT: 4,
  STEP_KEPLR_SETUP: 5,
  STEP_KEPLR_CONNECT: 6,
  STEP_CHECK_ADDRESS: 7,
  STEP_KEPLR_REGISTER: 8,
  STEP_DONE: 9,
  STEP_CHECK_GIFT: 10,
};

export { steps };
