const steps = {
  STEP_INIT: 0,
  STEP_NICKNAME_CHOSE: 1,
  STEP_NICKNAME_APROVE: 1.1,
  STEP_NICKNAME_INVALID: 1.2,
  STEP_RULES: 2,
  STEP_AVATAR_UPLOAD: 3,
  STEP_KEPLR_INIT: 4,
  STEP_KEPLR_INIT_CHECK_FNC: 4.1,
  STEP_KEPLR_SETUP: 5,
  STEP_KEPLR_CONNECT: 6,
  STEP_CHECK_ADDRESS: 7,
  STEP_CHECK_ADDRESS_CHECK_FNC: 7.1,
  STEP_ACTIVE_ADD: 7.2,
  STEP_KEPLR_REGISTER: 7.3,
  STEP_DONE: 7.4,
  STEP_CHECK_GIFT: 11,
};

export { steps };
