name: build_cyb_rebyc

on:
  push:
    branches:
      - rebyc

jobs:
  build_cyb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build cyb rebyc
        run: yarn build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
          CHAIN_ID: 'bostrom'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          BRANCH: rebyc-build
          FOLDER: build
          CLEAN: true
